// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrF_g0cErh4BTVQxYKLEUvXYQ2mKcB7qg',
    appId: '1:14441954063:web:bf435246023b3b8d5bdc7a',
    messagingSenderId: '14441954063',
    projectId: 'chatapp-69aca',
    authDomain: 'chatapp-69aca.firebaseapp.com',
    storageBucket: 'chatapp-69aca.firebasestorage.app',
    measurementId: 'G-R9WWE1CWCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyzPPfUlqNC2v-m0a7rsFxsCrGWPMWyqU',
    appId: '1:14441954063:android:d9ce6c7c6ad77eae5bdc7a',
    messagingSenderId: '14441954063',
    projectId: 'chatapp-69aca',
    storageBucket: 'chatapp-69aca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA02_NfD-8aIDX0obuB03ZgX7rhB879AB0',
    appId: '1:14441954063:ios:896b46ed695b8b9e5bdc7a',
    messagingSenderId: '14441954063',
    projectId: 'chatapp-69aca',
    storageBucket: 'chatapp-69aca.firebasestorage.app',
    iosBundleId: 'com.muneeb.mychatapps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA02_NfD-8aIDX0obuB03ZgX7rhB879AB0',
    appId: '1:14441954063:ios:1505afa1629b1f245bdc7a',
    messagingSenderId: '14441954063',
    projectId: 'chatapp-69aca',
    storageBucket: 'chatapp-69aca.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrF_g0cErh4BTVQxYKLEUvXYQ2mKcB7qg',
    appId: '1:14441954063:web:8edff1ecc55138f95bdc7a',
    messagingSenderId: '14441954063',
    projectId: 'chatapp-69aca',
    authDomain: 'chatapp-69aca.firebaseapp.com',
    storageBucket: 'chatapp-69aca.firebasestorage.app',
    measurementId: 'G-FQ6W93P460',
  );
}
